### ISSUE TITLE
Unresolved reference: import com.pro.audiotrimmer.databinding.LayoutAudioTrimmerBinding

### ISSUE THREAD

**Issue by ctnuun** [pro-softs/AudioTrimmer#4]
Hi, 

It seems like this library is missing from the project?
Please advise.

Thank you

**Comment by HafizaBushra** [comment]
Hi 
I have the same issue please Guide

**Comment by pro-softs** [comment]
It is the databinding import which is dynamically imported when the project is built, for each layout, use the updated library version for kotlin, it will be resolved
