### ISSUE TITLE
Audio wave wave form not being updated (same height)

### ISSUE THREAD

**Issue by irfankarim52** [pro-softs/AudioTrimmer#5]
One the file is sent to the audio trimmer view and .show() is called, the UI does not show different aptitudes of the audio may it be .wav or .mp3 file. The view just shows the whole wave at the same height.

**Comment by pro-softs** [comment]
Hi, you have to generate the samples for your .wav or .mp3 file and call setAudioSamples callback function to set those samples in the trimmer view. 
I am using native library like ffmpeg for the same. You can use something like this - 

https://github.com/lincollincol/Amplituda
